name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Test
        run: sbt ci publishLocal

      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        if: matrix.os == 'ubuntu-latest' && github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          
  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
